# Generated by Django 4.0.5 on 2022-07-15 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cursos_dictados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=200, verbose_name='Nombre')),
                ('horas', models.PositiveIntegerField(max_length=3, verbose_name='Horas')),
                ('institucion', models.CharField(max_length=200, verbose_name='Institucion')),
                ('anio', models.DateTimeField(max_length=4, verbose_name='Año')),
            ],
        ),
    ]
