# Generated by Django 4.0.5 on 2022-07-15 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos_dictados',
            name='horas',
            field=models.PositiveIntegerField(verbose_name='Horas'),
        ),
    ]
