# Generated by Django 4.0.5 on 2022-10-03 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0004_client_detsale_product_sale_delete_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='desc',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripcion'),
        ),
    ]
