# Generated by Django 4.0.5 on 2022-10-17 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0007_category_date_creation_category_date_update_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='date_update',
            new_name='date_updated',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='user_update',
            new_name='user_updated',
        ),
    ]
